// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTuVLkrTLDWpX3bGBsvNBeyyAn2xyfDGk',
    appId: '1:2664223364:web:acf5a541165494e781a8d1',
    messagingSenderId: '2664223364',
    projectId: 'todofire-98391',
    authDomain: 'todofire-98391.firebaseapp.com',
    storageBucket: 'todofire-98391.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb7OZ79Y_NJJlpbVNqCPXNO0i68F6x45o',
    appId: '1:2664223364:android:720397fab63df9df81a8d1',
    messagingSenderId: '2664223364',
    projectId: 'todofire-98391',
    storageBucket: 'todofire-98391.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFy_2F0UPCs-LMXqxlmKAZ6FLmXVhrpfw',
    appId: '1:2664223364:ios:b0bd2513deddbff281a8d1',
    messagingSenderId: '2664223364',
    projectId: 'todofire-98391',
    storageBucket: 'todofire-98391.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFy_2F0UPCs-LMXqxlmKAZ6FLmXVhrpfw',
    appId: '1:2664223364:ios:bb1c80e98a5f016781a8d1',
    messagingSenderId: '2664223364',
    projectId: 'todofire-98391',
    storageBucket: 'todofire-98391.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
